-- MySQL Script generated by MySQL Workbench
-- Tue Jul 20 18:33:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema citl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citl` DEFAULT CHARACTER SET utf8 ;
USE `citl` ;

-- -----------------------------------------------------
-- Table `citl`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citl`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `tel` INT NULL,
  `mail` TEXT NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citl`.`Import`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citl`.`Import` (
  `idimport` INT NOT NULL AUTO_INCREMENT,
  `doss` VARCHAR(45) NULL COMMENT 'Réception du dossier',
  `d1` VARCHAR(45) NULL COMMENT 'Date de reception du dossier',
  `fdi` VARCHAR(45) NULL COMMENT 'Etablissement de la Fiche de Déclaration à l\'Importation',
  `d2` VARCHAR(45) NULL COMMENT 'date d\'etabissement du fdi',
  `bsc` VARCHAR(45) NULL COMMENT 'Borderau de suivie de cargaison',
  `d3` VARCHAR(45) NULL COMMENT 'Date d\'etablissement du borderau de suivie de cargaison',
  `rfcv` VARCHAR(45) NULL COMMENT 'RApport final de classification et de Valeur',
  `d4` VARCHAR(45) NULL COMMENT 'date du rfcv',
  `td` VARCHAR(45) NULL COMMENT 'Tirage de Déclaration',
  `d5` VARCHAR(45) NULL COMMENT 'date du td',
  `dd` VARCHAR(45) NULL COMMENT 'Rapport de déclaration en douane',
  `d6` VARCHAR(45) NULL COMMENT 'date du dd',
  `pfp` VARCHAR(45) NULL COMMENT 'Paiement Frais Portuaire',
  `d7` VARCHAR(45) NULL COMMENT 'date du pfp',
  `liv` VARCHAR(45) NULL COMMENT 'Livraison',
  `d8` VARCHAR(45) NULL COMMENT 'date de livraison',
  `vsd` VARCHAR(45) NULL COMMENT 'Visiste douane',
  `d9` VARCHAR(45) NULL COMMENT 'date de visiste douane',
  `bed` VARCHAR(45) NULL COMMENT 'Bon à enlever douane',
  `d10` VARCHAR(45) NULL COMMENT 'date du bed',
  `codeImp` VARCHAR(45) NULL COMMENT 'Code du dossier de l\'importation',
  `statut` VARCHAR(45) NULL COMMENT 'Etat de l\'importation.\n0=en cours\n1= Soldé',
  `client_id` INT NOT NULL,
  PRIMARY KEY (`idimport`, `client_id`),
  INDEX `fk_Import_client_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Import_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `citl`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citl`.`Export`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citl`.`Export` (
  `idExport` INT NOT NULL AUTO_INCREMENT,
  `fret` VARCHAR(45) NULL COMMENT 'Demande de cotation du fret',
  `d1` VARCHAR(45) NULL COMMENT 'date de demande de cotation',
  `booking` VARCHAR(45) NULL COMMENT 'Demande de booking',
  `d2` VARCHAR(45) NULL COMMENT 'Date de demande de booking\n\n',
  `emb` VARCHAR(45) NULL COMMENT 'Embotage',
  `d3` VARCHAR(45) NULL COMMENT 'Date d\'embotage',
  `ae` VARCHAR(45) NULL COMMENT 'Etablissement de l\'attestation d\'exportation',
  `d4` VARCHAR(45) NULL COMMENT 'Date d\'attestion de l\'exportation',
  `chg` VARCHAR(45) NULL COMMENT 'Engagement de change',
  `d5` VARCHAR(45) NULL COMMENT 'date de chg',
  `td` VARCHAR(45) NULL COMMENT 'Tirage de declaration',
  `d6` VARCHAR(45) NULL COMMENT 'Date de TD',
  `ded` VARCHAR(45) NULL COMMENT 'Dépôt de declaration',
  `d7` VARCHAR(45) NULL COMMENT 'Date de depot de declaration en douane',
  `bd` VARCHAR(45) NULL COMMENT 'Bon à enlever douane',
  `d8` VARCHAR(45) NULL COMMENT 'date de la bd',
  `pfp` VARCHAR(45) NULL COMMENT 'Paiement fret portuaire',
  `d9` VARCHAR(45) NULL COMMENT 'Date paiemet fret portuaire',
  `rc` VARCHAR(45) NULL COMMENT 'Retrait connaissement',
  `d10` VARCHAR(45) NULL COMMENT 'date de rc',
  `dn` VARCHAR(45) NULL COMMENT 'depart navire',
  `d11` VARCHAR(45) NULL COMMENT 'date de depart navire',
  `codeexport` VARCHAR(45) NULL COMMENT 'code d\'export',
  `statut` VARCHAR(45) NULL COMMENT 'statut de l\'export\n0=en cours\n1=soldé',
  `client_id` INT NOT NULL,
  PRIMARY KEY (`idExport`, `client_id`),
  INDEX `fk_Export_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Export_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `citl`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citl`.`cotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citl`.`cotation` (
  `idcotation` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL COMMENT '1=export\n2=import',
  `nature` VARCHAR(45) NULL,
  `conteneur` VARCHAR(45) NULL COMMENT 'freezer\ntc40\"\"\ntc20\'\'\n',
  `pays_destination` VARCHAR(45) NULL,
  `poids` VARCHAR(45) NULL,
  `voie` VARCHAR(45) NULL COMMENT '1=martime\n2=aerien',
  `arrive` VARCHAR(45) NULL COMMENT 'port/aéroport de destination',
  `tel` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idcotation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citl`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citl`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
